import { Router } from 'express';
import { authRouter } from './auth.js';
import { holdingsRouter } from './holdings.js';
import { portfolioRouter } from './portfolio.js';
import { brokerageAccountsRouter } from './brokerageAccounts.js';
import { transactionsRouter } from './transactions.js';
import { csvImportsRouter } from './csvImports.js';
import { watchlistRouter } from './watchlist.js';
import { dividendsRouter } from './dividends.js';
import { newsRouter } from './news.js';
import { whaleTradesRouter } from './whaleTrades.js';
import { insiderTradesRouter } from './insiderTrades.js';
import { politicalTradesRouter } from './politicalTrades.js';
import { notificationsRouter } from './notifications.js';
import { providersRouter } from './providers.js';
import { marketContextRouter } from './marketContext.js';
import { requireAuth } from '../middleware/requireAuth.js';
import { attachUser } from '../middleware/attachUser.js';

export const apiRouter = Router();

apiRouter.get('/health', (_req, res) => res.json({ status: 'ok' }));
apiRouter.use('/auth', authRouter);

apiRouter.use(requireAuth);
apiRouter.use(attachUser);
apiRouter.use('/holdings', holdingsRouter);
apiRouter.use('/portfolio', portfolioRouter);
apiRouter.use('/brokerage-accounts', brokerageAccountsRouter);
apiRouter.use('/transactions', transactionsRouter);
apiRouter.use('/csv-imports', csvImportsRouter);
apiRouter.use('/watchlist', watchlistRouter);
apiRouter.use('/dividends', dividendsRouter);
apiRouter.use('/news', newsRouter);
apiRouter.use('/whale-trades', whaleTradesRouter);
apiRouter.use('/insider-trades', insiderTradesRouter);
apiRouter.use('/political-trades', politicalTradesRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/providers', providersRouter);
apiRouter.use('/market-context', marketContextRouter);
